services:
  db:
    image: postgres:16-alpine
    ports:
      - "5454:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: leaderboard
      POSTGRES_USER: leaderboard
      POSTGRES_PASSWORD: leaderboard
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}" ]
      interval: 30s
      timeout: 10s
      retries: 10
    networks:
      leaderboard:

  flyway:
    image: flyway/flyway
    volumes:
      - ./db:/flyway/sql
    command: -url=jdbc:postgresql://db:5432/leaderboard -user=leaderboard -password=leaderboard -connectRetries=60 migrate
    depends_on:
      db:
        condition: service_started
    networks:
      leaderboard:

  backend:
    build: Dockerfile
    image: leaderboard-api
    environment:
      SPRING_PROFILES_ACTIVE: container
    depends_on:
      - flyway
      - db
    networks:
      leaderboard:

networks:
  leaderboard:
    driver: bridge
volumes:
  pgdata: